### ISSUE TITLE
GHPage: instructions are outdated

### ISSUE THREAD

**Issue by arielj** [fastruby/pecas#75]
It instructs the user to run `rvm use 2.1.2@pecas`. The gemfile has `ruby '2.5.8'`, and it shouldn't need the `@pecas` part.

Maybe this shouldn't even be a step at all but a requirement listed before (people may not use rvm)

**Comment by etagwerker** [comment]
@arielj I fixed this with this commit: https://github.com/fastruby/pecas/commit/7c1ec3922e79c4983c8259b16c1ade6ccd45ad85
