### ISSUE TITLE
GHPage: Links point to `ombulabs` org

### ISSUE THREAD

**Issue by arielj** [fastruby/pecas#76]
Links are pointing to `github.com/ombulabs/pecas`, it works because it redirects them to fastruby, but I guess it's clearer if they just point to `github.com/fastruby/pecas`

**Comment by smithWEBtek** [comment]
Same issue for a link from `developer.nokotime.com

**Comment by etagwerker** [comment]
Fixed by https://github.com/fastruby/pecas/commit/1027e0da814e6cb1e30ed5ec2b5475e6848b6bb2
