### ISSUE TITLE
[BUG] Stop using FactoryGirl, start using FactoryBot

### ISSUE THREAD

**Issue by etagwerker** [fastruby/pecas#84]
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

`main` branch. 

**Expected behavior:**

Should be using FactoryBot.

**Actual behavior:**

Still using FactoryGirl.

**Steps to reproduce:**

1. Step 1: Run test suite (bundle exec rspec spec)
2. Step 2: See the deprecation warning

**Logs**

Console output: 

```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from require at /Users/etagwerker/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81)
```

**I will abide by the [code of conduct](https://github.com/fastruby/pecas/blob/main/code-of-conduct.md)**

**Comment by bhavik2936** [comment]
I would like to work on the same!

**Comment by bhavik2936** [comment]
On successful merge of branch #88, it would be better to close the issue.
