### ISSUE TITLE
Support/document running the app without using Docker

### ISSUE THREAD

**Issue by arielj** [fastruby/pecas#92]
**Branch/Commit:**

Main branch.

**Describe the feature:**

As a developer, I want to be able to run the app without using Docker if needed.

**Problem:**

I only see instructions on how to run the app using Docker, and the default database.yml will probably not work when running the app standalone.

**I will abide by the [code of conduct](https://github.com/fastruby/pecas/blob/main/code-of-conduct.md)**

**Comment by kindoflew** [comment]
Me and Francois paired on #90 the other day and after we changed `config/database.yml` like in [this comment](https://github.com/fastruby/pecas/pull/90#issuecomment-944454041) we got it running just with `rails server`.
